version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
    commit-message:
      prefix: ci
  - package-ecosystem: npm
    directory: /.github/ci
    schedule:
      interval: weekly
    groups:
      docs-tooling:
        patterns: ['*']
    commit-message:
      prefix: ci
  - package-ecosystem: docker
    directory: /.github/ci
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
