# Arasaka palette overlay. Load after the user's main Powerlevel10k config.
typeset -g POWERLEVEL9K_DIR_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=244
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=250
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=196
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=196
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=255
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=255
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=244
typeset -g POWERLEVEL9K_TIME_FOREGROUND=244
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=196
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=250
